# steps:
#   # Build the container image
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "build",
#         "-t",
#         "gcr.io/stack-sync-challenge-458618/python-execution-api:$COMMIT_SHA",
#         ".",
#       ]

#   # Push the container image to Container Registry
#   - name: "gcr.io/cloud-builders/docker"
#     args:
#       [
#         "push",
#         "gcr.io/stack-sync-challenge-458618/python-execution-api:$COMMIT_SHA",
#       ]

#   # Deploy container image to Cloud Run
#   - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#     entrypoint: gcloud
#     args:
#       - "run"
#       - "deploy"
#       - "python-execution-api"
#       - "--image"
#       - "gcr.io/stack-sync-challenge-458618/python-execution-api:$COMMIT_SHA"
#       - "--region"
#       - "us-central1"
#       - "--platform"
#       - "managed"
#       - "--allow-unauthenticated"
#       - "--memory"
#       - "512Mi"
#       - "--cpu"
#       - "1"
#       - "--concurrency"
#       - "50"
#       - "--timeout"
#       - "60s"

# images:
#   - "gcr.io/stack-sync-challenge-458618/python-execution-api:$COMMIT_SHA"

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/python-execution-api:latest", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/python-execution-api:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "python-execution-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/python-execution-api:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "60s"

images:
  - "gcr.io/$PROJECT_ID/python-execution-api:latest"
